version: '3'
services:
  saturn:
    container_name: saturn
    image: xamber/saturn-app:release-${app_version}
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - orbit

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    networks:
      - orbit

  frontend:
    container_name: frontend
    image: xamber/saturn-frontend:release-${frontend_version}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - saturn
    networks:
      - orbit
    volumes:
      - ~/ssl/:/etc/nginx/certs/

networks:
  orbit:
    driver: bridge