version: '3'
services:
  saturn:
    container_name: saturn
    build:
      context: .
      dockerfile: ./build/package/Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - orbit

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    networks:
      - orbit

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./../build/frontend/Dockerfile
    ports:
      - 80:80
    depends_on:
      - saturn
    networks:
      - orbit

networks:
  orbit:
    driver: bridge