# This is a basic workflow to help you get started with Actions

name: Build and push Docker - Frontend

# Controls when the action will run. 
on:
  push:
    tags:
      - v*
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/saturn-app:release-${{steps.tag.outputs.tag}}
      - name: tag digest
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}/saturn-app:release-${{steps.tag.outputs.tag}}
