# This is a basic workflow to help you get started with Actions

name: Build and push Docker - Backend

# Controls when the action will run. 
on:
  push:
    tags:
      - v*
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Git Tag
        run: echo ::set-env name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/package/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/saturn-app:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
